package frontend;

import com.auction.services.AuctionSystem;
import com.auction.entities.User;

import javax.swing.*;
import java.awt.*;

public class SignupPage extends JPanel {
    private JTextField nameField, emailField, phoneField, addressField;
    private JPasswordField passField;
    private JComboBox<String> roleCombo;

    public SignupPage(MainFrame frame, AuctionSystem system) {
        setBackground(Theme.BACKGROUND);
        setLayout(new GridBagLayout());

        JPanel signupBox = new JPanel();
        signupBox.setBackground(Theme.CARD_BG);
        signupBox.setPreferredSize(new Dimension(450, 500));
        signupBox.setLayout(new BoxLayout(signupBox, BoxLayout.Y_AXIS));
        signupBox.setBorder(BorderFactory.createEmptyBorder(30, 40, 30, 40));

        JLabel titleLabel = new JLabel("Create an Account");
        titleLabel.setFont(Theme.TITLE_FONT);
        titleLabel.setForeground(Theme.TEXT_DARK);
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        nameField = createTextField();
        emailField = createTextField();
        passField = new JPasswordField();
        passField.setMaximumSize(new Dimension(350, 35));
        passField.setFont(Theme.REGULAR_FONT);
        
        phoneField = createTextField();
        addressField = createTextField();
        
        roleCombo = new JComboBox<>(new String[]{"BUYER", "SELLER"});
        roleCombo.setMaximumSize(new Dimension(350, 35));
        roleCombo.setFont(Theme.REGULAR_FONT);

        JButton registerBtn = Theme.createButton("Sign Up", Theme.PRIMARY_COLOR);
        registerBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
        registerBtn.addActionListener(e -> {
            String name = nameField.getText();
            String email = emailField.getText();
            String pwd = new String(passField.getPassword());
            String phone = phoneField.getText();
            String address = addressField.getText();
            String role = (String) roleCombo.getSelectedItem();

            if (name.isEmpty() || email.isEmpty() || pwd.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name, Email, and Password are required.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Create user with a temporary ID (will be generated by DB later)
            // Using 0 as a placeholder ID; in reality, DB provides this.
            int tempId = (int)(Math.random() * 10000); 
            User newUser = new User(tempId, name, email, pwd, phone, address, role);
            
            system.registerUser(newUser);
            JOptionPane.showMessageDialog(this, "Account created successfully! Please login.", "Success", JOptionPane.INFORMATION_MESSAGE);
            frame.navigateTo("LOGIN");
        });

        JButton backBtn = new JButton("Back to Login");
        backBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
        backBtn.setForeground(Theme.PRIMARY_COLOR);
        backBtn.setContentAreaFilled(false);
        backBtn.setBorderPainted(false);
        backBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backBtn.addActionListener(e -> frame.navigateTo("LOGIN"));

        signupBox.add(titleLabel);
        signupBox.add(Box.createRigidArea(new Dimension(0, 20)));
        signupBox.add(new JLabel("Full Name*"));
        signupBox.add(nameField);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(new JLabel("Email Address*"));
        signupBox.add(emailField);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(new JLabel("Password*"));
        signupBox.add(passField);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(new JLabel("Phone Number"));
        signupBox.add(phoneField);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(new JLabel("Address"));
        signupBox.add(addressField);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(new JLabel("Role"));
        signupBox.add(roleCombo);
        signupBox.add(Box.createRigidArea(new Dimension(0, 20)));
        signupBox.add(registerBtn);
        signupBox.add(Box.createRigidArea(new Dimension(0, 10)));
        signupBox.add(backBtn);

        add(signupBox);
    }

    private JTextField createTextField() {
        JTextField field = new JTextField();
        field.setMaximumSize(new Dimension(350, 35));
        field.setFont(Theme.REGULAR_FONT);
        return field;
    }
}
