-- ORACLE XE 11g/older compatible DIGITAL AUCTION SYSTEM

-- Optional drops
/*
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BID CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE AUCTION_EVENT CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP SEQUENCE users_seq;
DROP SEQUENCE category_seq;
DROP SEQUENCE auction_seq;
DROP SEQUENCE item_seq;
DROP SEQUENCE bid_seq;
DROP SEQUENCE payment_seq;
*/

CREATE TABLE USERS (
user_id NUMBER PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
email VARCHAR2(100) UNIQUE NOT NULL,
password VARCHAR2(255) NOT NULL,
phone VARCHAR2(20),
address VARCHAR2(255),
role VARCHAR2(20) NOT NULL CHECK (role IN ('ADMIN','SELLER','BUYER')),
rating NUMBER(3,2) DEFAULT 0.0
);
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE CATEGORY (
category_id NUMBER PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
description CLOB
);
CREATE SEQUENCE category_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE AUCTION_EVENT (
auction_id NUMBER PRIMARY KEY,
title VARCHAR2(200) NOT NULL,
description CLOB,
start_time TIMESTAMP NOT NULL,
end_time TIMESTAMP NOT NULL,
status VARCHAR2(20) DEFAULT 'UPCOMING' CHECK (status IN ('UPCOMING','ONGOING','COMPLETED')),
conducted_by NUMBER NOT NULL,
CONSTRAINT fk_auction_conducted_by FOREIGN KEY (conducted_by) REFERENCES USERS(user_id)
);
CREATE SEQUENCE auction_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE ITEM (
item_id NUMBER PRIMARY KEY,
name VARCHAR2(200) NOT NULL,
description CLOB,
base_price NUMBER(12,2) NOT NULL,
image_url VARCHAR2(500),
status VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','SOLD','UNSOLD')),
seller_id NUMBER NOT NULL,
auction_id NUMBER NOT NULL,
category_id NUMBER NOT NULL,
CONSTRAINT fk_item_seller FOREIGN KEY (seller_id) REFERENCES USERS(user_id),
CONSTRAINT fk_item_auction FOREIGN KEY (auction_id) REFERENCES AUCTION_EVENT(auction_id),
CONSTRAINT fk_item_category FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id)
);
CREATE SEQUENCE item_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE BID (
bid_id NUMBER PRIMARY KEY,
bid_amount NUMBER(12,2) NOT NULL,
bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
item_id NUMBER NOT NULL,
buyer_id NUMBER NOT NULL,
CONSTRAINT fk_bid_item FOREIGN KEY (item_id) REFERENCES ITEM(item_id),
CONSTRAINT fk_bid_buyer FOREIGN KEY (buyer_id) REFERENCES USERS(user_id)
);
CREATE SEQUENCE bid_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE PAYMENT (
payment_id NUMBER PRIMARY KEY,
payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
amount NUMBER(12,2) NOT NULL,
status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING','SUCCESS','FAILED')),
item_id NUMBER NOT NULL,
buyer_id NUMBER NOT NULL,
CONSTRAINT fk_payment_item FOREIGN KEY (item_id) REFERENCES ITEM(item_id),
CONSTRAINT fk_payment_buyer FOREIGN KEY (buyer_id) REFERENCES USERS(user_id)
);
CREATE SEQUENCE payment_seq START WITH 1 INCREMENT BY 1;

COMMIT;
