-- ==============================================================================
-- ORACLE DATABASE SETUP SCRIPT: DIGITAL AUCTION SYSTEM
-- ==============================================================================
-- INSTRUCTIONS:
-- 1. Open Oracle SQL Developer, SQL*Plus, or any Oracle DB client.
-- 2. Connect to your Oracle database using your credentials.
-- 3. To run this file via SQL*Plus, open your command prompt and use: 
--    @oracle_db_setup.sql
-- 4. In SQL Developer, simply open this file, hit CTRL+A, and execute as a script (F5).
-- ==============================================================================

-- STEP 1: (Optional) Drop existing tables if you are resetting the database
-- Note: We drop tables in the reverse order of dependencies to avoid foreign key conflicts.
/*
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BID CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE AUCTION_EVENT CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
*/

-- STEP 2: Create USERS table
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    phone VARCHAR2(20),
    address VARCHAR2(255),
    role VARCHAR2(20) NOT NULL CHECK (role IN ('ADMIN', 'SELLER', 'BUYER')),
    rating NUMBER(3, 2) DEFAULT 0.0
);

-- STEP 3: Create CATEGORY table
CREATE TABLE CATEGORY (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB -- CLOB is used in Oracle for longer text fields
);

-- STEP 4: Create AUCTION_EVENT table
CREATE TABLE AUCTION_EVENT (
    auction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'UPCOMING' CHECK (status IN ('UPCOMING', 'ONGOING', 'COMPLETED')),
    conducted_by NUMBER NOT NULL,
    CONSTRAINT fk_auction_conducted_by FOREIGN KEY (conducted_by) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- STEP 5: Create ITEM table
CREATE TABLE ITEM (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    description CLOB,
    base_price NUMBER(12, 2) NOT NULL,
    image_url VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'SOLD', 'UNSOLD')),
    seller_id NUMBER NOT NULL,
    auction_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT fk_item_seller FOREIGN KEY (seller_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_auction FOREIGN KEY (auction_id) REFERENCES AUCTION_EVENT(auction_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_category FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id) ON DELETE CASCADE
);

-- STEP 6: Create BID table
CREATE TABLE BID (
    bid_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_amount NUMBER(12, 2) NOT NULL,
    bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    item_id NUMBER NOT NULL,
    buyer_id NUMBER NOT NULL,
    CONSTRAINT fk_bid_item FOREIGN KEY (item_id) REFERENCES ITEM(item_id) ON DELETE CASCADE,
    CONSTRAINT fk_bid_buyer FOREIGN KEY (buyer_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- STEP 7: Create PAYMENT table
CREATE TABLE PAYMENT (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    amount NUMBER(12, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    item_id NUMBER NOT NULL,
    buyer_id NUMBER NOT NULL,
    CONSTRAINT fk_payment_item FOREIGN KEY (item_id) REFERENCES ITEM(item_id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_buyer FOREIGN KEY (buyer_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- STEP 8: Commit the changes
COMMIT;

-- Database creation complete. You can now start inserting sample data.
